export const Countries = {
  ARG: 'Argentina',
  AUS: 'Austrália',
  BEL: 'Bélgica',
  BRA: 'Brasil',
  GAN: 'Canadá',
  CMR: 'Camarões',
  CRC: 'Costa Rica',
  CRO: 'Croácia',
  DEN: 'Dinamarca',
  ECU: 'Ecuador',
  ENG: 'Inglaterra',
  ESP: 'Espanha',
  FRA: 'França',
  GER: 'Alemanha',
  GHA: 'Gana',
  HOL: 'Holanda',
  IRN: 'Irã',
  JPN: 'Japão',
  KOR: 'Coréia do Sul',
  KSA: 'Arábia Saudita',
  MAR: 'Marrocos',
  MEX: 'México',
  POL: 'Polônia',
  POR: 'Portugal',
  QAT: 'Catar',
  SEN: 'Senegal',
  SRB: 'Sérvia',
  SUI: 'Suiça',
  TUN: 'Tunísia',
  USA: 'Estados Unidos',
  URU: 'Uruguai',
  WAL: 'Gales',
}

//ALEMANHA, JAPAO, BELGICA
